# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: teal

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'University of Michigan - Industrial & Operations Engineering'
    description: 'Qingyuan Xu Academic Website — PhD student in Operations Research at the University of Michigan, focusing on stochastic and robust optimization.'
 #  twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Qingyuan Xu"

# Site footer
footer:
  copyright:
    notice: '© 2025 Qingyuan Xu | Feel free to connect.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false
